### ISSUE TITLE
Multilingual Interstellar Support

### ISSUE THREAD

**Issue by fadillzzz** [Kramar1337/Tower-of-Fantasy-AHK-flex#16]
I'm not sure if the feature is ready yet or not, but I noticed you added an AFK Interstellar feature but it seems to only work for the English language. So if a post was made in a different language, the script wouldn't be able to detect it via ImageSearch.

Do you think you can make it so that the script will loop through multiple images in a folder until a match is found instead? That way, I can create images for different languages and have the script automatically pick them up during runtime.
Maybe have a folder structure that's like the following perhaps:
```
data
|__ pix
|____ 1440p
|______ col-blu
|________ en.png
|________ ru.png
|________ zh.png
```

Also, for the "Join" button perhaps instead of using ImageSearch, you could try PixelSearch? I don't know how well it'd work though. I don't have a lot of experience with this kind of stuff.

**Comment by Kramar1337** [comment]
At some point on my alternate account, I needed an accelerated leveling through "Interstellar" and I tried to do "AFK Interstellar". I ran into a lot of issues and put this feature on hold. AHK does not know how to work correctly with image search and you need to come up with something simple and effective.
I did not delete the code and will add it later, now other functions are in priority:
 - Autofarm PVP arena
 - Autosearch frontier via text search
 - Internet cutter through firewall

AFK Interstellar looks interesting, but I have not figured out how it will be implemented so that it works well for everyone.

**Comment by fadillzzz** [comment]
I see. It's definitely a feature that'd be really nice to have, although I can imagine that it'd be a bit tricky to implement.

> Internet cutter through firewall

What is this for exactly?

**Comment by Kramar1337** [comment]
in some places there is no "leave the dungeon" button, also I do not see the button to change the server? I need to quit the game completely, it's annoying. I turn off the Internet for the game and throws me into the main menu. I will do it with 1 click
